version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB} # Optional: specify a default database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8081:80'
    networks:
      - db-network

volumes:
  postgres_data:

networks:
  db-network:
    external: true
